### ISSUE TITLE
Progress on your project TermPlot

### ISSUE THREAD

**Issue by yungyuc** [hsjts0u/TermPlot#1]
I have not seen code being checked in to your project TermPlot.  Do you need help?

**Comment by hsjts0u** [comment]
I have begun work already, but just haven't pushed progress from my local machine to this remote repo. Thanks for checking up on my progress. I think I should be fine! I'll try to push updates as soon as things are in partial working order.

**Comment by yungyuc** [comment]
Sounds good.  If you want to discuss something in your code, please open an issue in your repository and tag me in it.
